CC=gcc
CFLAGS=-c -Wall

all:pyvm

pyvm: pymain.o operation.o
	$CC pymain.o operation.o

pymain.o: pymain.c opearation.c pyvm.h opcod.h
	$CC $CFLAGS pymain.c operation.c pyvm.h opcod.h

operation.o: operation.c operation.h pyvm.h
	$CC $CFLAGS operation.c pyvm.h 




